name: Submit a Record of publication
description: Submit a record of publication
title: ISSUE TITLE
projects: NASA-IMPACT/87
body:
  - type: markdown
    attributes:
      value: |
        This is the SNWG MO publication Submission Form. The values you add will be converted to a properly formatted Issue for the SNWG Management Office.
  - type: dropdown
    id: SNWG-project
    attributes:
      label: SNWG Project
      description: Which SNWG project is this publication affiliated with/supporting?
      options: 
        - C1 - ADMG
        - C1 - CSDA
        - C1 - DCD
        - C1 - HLS
        - C2 - OPERA (if applicable to GSWx, DIST, or DISP specifically, please note that)
        - C2 - AC-GEOS
        - C2 - Freeboard and Ice Thickness
        - C2 - Internet of Animals
        - C2 - NISAR Soil Moisture
        - C2 - SatCORPS
        - C2 - Water Quality Product
        - C3 - Air Quality Product
        - C3 - Planetary Boundary Layer
        - C3 - Sea Ice
        - C3 - TEMPO NRT
        - C3 - HLS- Vegitation Indices
        - Other (Please specify below)
      default: 0
    validations: 
      required: true
  - type: dropdown
    id: publication-type
    attributes:
      label: Publication type
      description: WWhat type of file are you submitting?
      options:
        - Dataset
        - Event
        - Lesson
        - Journal article
        - Poster
        - Presentation
        - Publication / Book or book chapter
        - Publication / Conference Paper
        - Publication / Data paper
        - Publication / Journal or Journal article
        - Publication / Report
        - Publication / Software documentation
        - Publication / Standards
        - Software (open acces/source)
        - other
      default: 0
    validations:
      required: true
  - type: input
    id: DOI
    attributes:
      label: Existing Digital Object Identifier (DOI)
      description: Enter existing DOI for this submission. 
      placeholder: A DOI allows your upload to be easily and unambiguously cited. Example - 10.1234/fun.num
  - type: input 
    id: Date-of-publishing
    attributes:
      label: Publication Date
      description: When was your submission published and available to the public? 
      placeholder: 2023 March 15
    validations:
      required: true
  - type: input
    id: creators
    attributes:
      label: Creators
      description: Who created the resource being submitted
      placeholder: Last name, First Name
    validations: 
      required: true
  - type: input
    id: publisher
    attributes:
      label: Publisher
      description: The publisher is used to formulate the citation, so consider the prominence of the role.
    validations: 
      required: true
  - type: input
    id: contributors
    attributes:
      label: Contributors
      description: Who contributed to the resource being submitted
      placeholder: Last name, First Name
    validations: 
      required: true
  - type: textarea
    id: funding
    attributes:
      label: funding
      description: Any awards and funders that apply 
      placeholder: Last name, First Name
    validations: 
      required: true  
  - type: input
    id: journal-info
    attributes: 
      label: Journal-Info
      description: Journal Title and International Standard Serial Number (ISSN), if applicable
      placeholder: Title of the journal on which the article was published
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add two to three sentences that explain the context of this publication and what it achieved.
      placeholder: To consider when completing this section...
        - When answering the question, team members should keep in mind several considerations to provide a comprehensive and informative response - 
        - 1. Clarity and Conciseness. Ensure that the sentences are clear and concise. Avoid unnecessary jargon or technical details that might confuse readers who are not intimately familiar with the software or the subject matter.
        - 2. Contextual Information. Provide essential background information about the software and the problem it addresses. Explain why this publication is significant and relevant to the field.
        - 3. Achievements and Contributions. Clearly outline the achievements and contributions of the publication. What did the software or the research achieve? Highlight specific results or outcomes.
        - 4. Impact and Significance. Describe the broader impact and significance of the publication. How does it contribute to the field, and how might it benefit users, researchers, or the organization?
        - 5. Target Audience. Consider the intended audience for the form and tailor the response accordingly. If it's for a technical audience, you can delve into more technical details. If it's for a broader audience, use layman's terms.
        - 6. Measurable Metrics. If applicable, include measurable metrics such as increased user engagement, reduced errors, improved performance, or any other quantifiable outcomes to demonstrate the success of the publication.
        - 7. Citations and References. If the publication builds on or references previous work, make sure to include relevant citations or references to acknowledge prior research or work that this publication builds upon.
        - 8. Future Implications. Discuss any potential future implications or applications of the publication. How might this work lead to further developments or research opportunities?
        - 9. Avoiding Overstatements. While it is important to highlight achievements, be cautious not to overstate the impact or significance. Keep the description accurate and balanced.
        - 10. Relevance to the Form Purpose. Ensure that the response directly addresses the purpose of the form, which is to report publications related to the software. Avoid unrelated or tangential information.
        - 11. Proofreading. Review and proofread the response for grammar and clarity. A well-structured and error-free response is more likely to effectively convey the message.
        - 12. Feedback and Collaboration. Consider seeking input or feedback from colleagues or peers who are familiar with the publication to ensure that the response accurately represents the work.
        - By keeping these considerations in mind, team members can provide informative, meaningful, and well-structured responses to the question, helping others understand the context and achievements of their publications related to the software.
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related Files
      description: |
        Add cards on which this issue is related
        Github automatically provides a list of possible issues if you start by typing a `#`
      placeholder: link to related Github repository, issues, or projects
    validations:
      required: false
